version: "2"
checks:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
plugins:
  rubocop:
    enabled: true
  duplication:
    enabled: true
  reek:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.css"
  - "**.coffee"
