---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  rubocop:
    emabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.css"
  - "**.coffee"
  - "**.js"
exclude_paths:
- spec/**/*
- vendor/**/*
