version: "2"
plugins:
  duplication:
    enabled: true
  config:
    languages:
    - ruby
  rubocop:
    enabled: true
  duplication:
    enabled: true
  reek:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.css"
  - "**.coffee"
