detectors:
  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    exclude:
      - 'Inquisition::CLI#execute'

  TooManyInstanceVariables:
    max_instance_variables: 6

  TooManyConstants:
    max_constants: 7
