detectors:
  IrresponsibleModule:
    enabled: false

  NestedIterators:
    ignore_iterators:
      - around

  TooManyStatements:
    exclude:
      - 'Inquisition::Options#define_options'

  Attribute:
    exclude:
      - 'Inquisition::Configuration#output'

  UtilityFunction:
    exclude:
      - 'Inquisition::Executor::Version#call'
