detectors:
  IrresponsibleModule:
    enabled: false

directories:
  "spec/dummy":
    TooManyStatements:
      enabled: false
    UtilityFunction:
      enabled: false
    FeatureEnvy:
      enabled: false
