detectors:
  IrresponsibleModule:
    enabled: false

  NestedIterators:
    ignore_iterators:
      - around
      - open

  TooManyStatements:
    exclude:
      - initialize
      - Inquisition::Options#define_options

  Attribute:
    exclude:
      - Inquisition::Configuration#output

  UtilityFunction:
    exclude:
      - Inquisition::Executor::Version#call

  DuplicateMethodCall:
    exclude:
      - Inquisition::DeepSymbolizeKeys#_deep_symbolize_keys_in_object
