detectors:
  IrresponsibleModule:
    enabled: false

  NestedIterators:
    ignore_iterators:
      - around

  TooManyStatements:
    exclude:
      - 'Inquisition::Options#define_options'
      - 'Inquisition::Issue#initialize'

  Attribute:
    exclude:
      - 'Inquisition::Configuration#output'

  UtilityFunction:
    exclude:
      - 'Inquisition::Executor::Version#call'

  LongParameterList:
    exclude:
      - 'Inquisition::Issue#initialize'
