detectors:
  UnusedPrivateMethod:
    enabled: true

  IrresponsibleModule:
    enabled: false

  UtilityFunction:
    enabled: false

  UnusedPrivateMethod:
    enabled: false

  ControlParameter:
    enabled: false

  InstanceVariableAssumption:
    enabled: false

  FeatureEnvy:
    enabled: false

  TooManyMethods:
    enabled: false

  TooManyConstants:
    exclude:
      - 'Inquisition::BaseConfig'

  TooManyStatements:
    exclude:
      - 'Inquisition::Core::Presenters::Elements::Html::Static::LineChart::TopTablesWithErrorsLineChartPresenter#add_items'
