require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Include:
    - '**/Rakefile'
    - 'lib/**/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15
  Exclude:
    - lib/inquisition/auditors/backend/installer.rb
    - lib/inquisition/auditors/backend/runner.rb

Metrics/ClassLength:
  Exclude:
    - lib/inquisition/core/base_formatter.rb
    - lib/inquisition/core/presenters/menu_items_presenter.rb
