require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.4

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context

RSpec/DescribeClass:
  Exclude:
    - spec/inquisition/tasks/**/*_spec.rb

RSpec/FilePath:
  Exclude:
    - spec/integration/**/*_spec.rb
