require:
  - rubocop-rspec
  - rubocop-performance

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/inquisition/bundler/audit/runner_spec.rb'

RSpec/ExampleLength:
  Max: 6
  Exclude:
    - 'spec/**/*.rb'

RSpec/MessageSpies:
  Exclude:
    - 'spec/inquisition/bundler/audit/runner_spec.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/inquisition/options.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/**/*.rb'
