require:
  - rubocop-rspec
  - rubocop-performance

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - describe

RSpec/DescribeClass:
  Exclude:
    - spec/inquisition/tasks/**/*_spec.rb

RSpec/FilePath:
  Exclude:
    - spec/integration/**/*_spec.rb
