AllCops:
  Include:
    - '**/Rakefile'
    - 'lib/**/*.rb'
  Exclude:
    - 'spec/support/**/*'
    - 'spec/spec_helper.rb'
Documentation:
  Enabled: false
LineLength:
  Max: 120
Metrics/MethodLength:
  Exclude:
    - lib/inquisition/auditors/backend/installer.rb
    - lib/inquisition/auditors/backend/runner.rb
