require:
  - rubocop-rspec
  - rubocop-performance

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/MessageSpies:
  Exclude:
    - 'spec/**/*.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/**/*.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*.rb'
