default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: postgres

development:
  <<: *default
  database: dummy

test:
  <<: *default
  database: test_dummy

production:
  <<: *default
  database: prod_dummy
