default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: postgres

development:
  <<: *default
  host: <%= ENV.fetch('PGHOST') { 'localhost' } %>
  username: <%= ENV.fetch('PGUSER') { 'postgres' } %>
  database: <%= ENV.fetch('POSTGRES_DB') { 'dummy' } %>

test:
  <<: *default
  host: <%= ENV.fetch('PGHOST') { 'localhost' } %>
  username: <%= ENV.fetch('PGUSER') { 'postgres' } %>
  database: <%= ENV.fetch('POSTGRES_DB') { 'test_dummy' } %>

production:
  <<: *default
  host: <%= ENV.fetch('PGHOST') { 'localhost' } %>
  username: <%= ENV.fetch('PGUSER') { 'postgres' } %>
  database: <%= ENV.fetch('POSTGRES_DB') { 'prod_dummy' } %>
