defaults: &defaults
  working_directory: ~/inquisition
  docker:
    - image: circleci/ruby:2.5.1-node
      environment:
        - RAILS_ENV: test
  environment:
    CIRCLE_TEST_REPORTS: test_reports
    CIRCLE_ARTIFACTS: tmp/coverage

references:
  restore_bundle_cache: &restore_bundle_cache
    restore_cache:
      keys:
        - inquisition-{{ checksum "Gemfile.lock" }}

  bundle_install: &bundle_install
    run:
      name: Installing gems
      command: bundle install --path vendor/bundle

  save_bundle_cache: &save_bundle_cache
    save_cache:
      key: inquisition-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle

  install_undercover_dependencies: &install_undercover_dependencies
    run:
      name: Installing dependency for undercover gem
      command: sudo apt-get update && sudo apt-get install cmake

  run_overcommit: &run_overcommit
    run:
      name: Running overcommit
      command: |
        bundle exec overcommit -s
        SKIP=AuthorEmail,AuthorName bundle exec overcommit -r

  run_tests: &run_tests
    run:
      name: Running tests
      command: bundle exec rspec

  run_coverage: &run_coverage
    run:
      name: Coverage
      command: bundle exec undercover

  setup_code_climate: &setup_code_climate
    run:
      name: Install Code Climate Test Reporter
      command: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
  run_coverage_codeclimate: &run_coverage_codeclimate
    run:
      name: Code Climate Test Coverage
      command: |
        ./cc-test-reporter format-coverage -t simplecov -o "coverage/codeclimate.json"

version: 2

jobs:
  linters:
    <<: *defaults
    steps:
      - checkout
      - <<: *install_undercover_dependencies
      - <<: *restore_bundle_cache
      - <<: *bundle_install
      - <<: *save_bundle_cache
      - <<: *run_overcommit

  tests:
    <<: *defaults
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_TEST_REPORTS $CIRCLE_ARTIFACTS
      - <<: *install_undercover_dependencies
      - <<: *restore_bundle_cache
      - <<: *bundle_install
      - <<: *save_bundle_cache
      - <<: *run_tests
      - <<: *run_coverage
      - <<: *setup_code_climate
      - <<: *run_coverage_codeclimate

      - store_test_results:
          path: $CIRCLE_TEST_REPORTS
      - store_artifacts:
          path: $CIRCLE_ARTIFACTS
      - store_artifacts:
          path: coverage/codeclimate.json

workflows:
  version: 2
  build:
    jobs:
      - linters
      - tests
