require 'inquisition/config/initializers/i18n'
require 'inquisition/outputer'
require 'inquisition/cli'

require 'inquisition/errors/base_error'
require 'inquisition/errors/base_config_absense_error'
require 'inquisition/errors/no_gem_error'
require 'inquisition/errors/no_config_file_error'
require 'inquisition/errors/invalid_ruby_version_error'
require 'inquisition/errors/additional_software_absence_error'

require 'inquisition/authorization'
require 'inquisition/builder'
require 'inquisition/configure'
require 'inquisition/base_config'

require 'inquisition/core/configure'
require 'inquisition/core/base_formatter'
require 'inquisition/core/base_installer'
require 'inquisition/core/base_runner'
require 'inquisition/core/configurers/copy_file_configure'
require 'inquisition/core/configurers/update_file_configure'

require 'inquisition/core/checker'
require 'inquisition/core/checkers/gem_checker'
require 'inquisition/core/checkers/exist_file_checker'
require 'inquisition/core/checkers/ruby_version_checker'
require 'inquisition/core/checkers/additional_software_checker'

require 'inquisition/auditors/installer'
require 'inquisition/auditors/backend/installer'
require 'inquisition/auditors/frontend/installer'
require 'inquisition/auditors/runner'
require 'inquisition/auditors/backend/runner'
require 'inquisition/auditors/frontend/runner'

require 'inquisition/auditors/backend/bullet/installer'
require 'inquisition/auditors/backend/fasterer/installer'
require 'inquisition/auditors/backend/reek/installer'
require 'inquisition/auditors/backend/haml_lint/installer'
require 'inquisition/auditors/backend/lol_dba/installer'
require 'inquisition/auditors/backend/railroady/installer'
require 'inquisition/auditors/backend/rails_erd/installer'
require 'inquisition/auditors/backend/rubocop/installer'
require 'inquisition/auditors/backend/rails_best_practices/installer'
require 'inquisition/auditors/backend/rubocop_rspec/installer'
require 'inquisition/auditors/backend/ruby_lint/installer'
require 'inquisition/auditors/backend/simplecov/installer'
require 'inquisition/auditors/backend/slim_lint/installer'
require 'inquisition/auditors/backend/yamllint/installer'
require 'inquisition/auditors/backend/active_record_doctor/installer'
require 'inquisition/auditors/frontend/i18n_tasks/installer'

require 'inquisition/auditors/backend/rubocop/formatter'
require 'inquisition/auditors/backend/fasterer/formatter'
require 'inquisition/auditors/backend/rails_best_practices/formatter'
require 'inquisition/auditors/backend/dawnscanner/formatter'
require 'inquisition/auditors/backend/bundler_audit/formatter'
require 'inquisition/auditors/backend/reek/formatter'
require 'inquisition/auditors/backend/ruby_lint/formatter'
require 'inquisition/auditors/backend/yamllint/formatter'
require 'inquisition/auditors/backend/lol_dba/formatter'
require 'inquisition/auditors/backend/active_record_doctor/formatters/extraneous_indexes_formatter'
require 'inquisition/auditors/backend/active_record_doctor/formatters/missing_foreign_keys_formatter'
require 'inquisition/auditors/backend/active_record_doctor/formatters/missing_non_null_constraint_formatter'
require 'inquisition/auditors/backend/active_record_doctor/formatters/missing_presence_validation_formatter'
require 'inquisition/auditors/backend/active_record_doctor/formatters/missing_unique_indexes_formatter'
require 'inquisition/auditors/backend/active_record_doctor/formatters/undefined_table_references_formatter'
require 'inquisition/auditors/backend/active_record_doctor/formatters/unindexed_deleted_at_formatter'
require 'inquisition/auditors/backend/active_record_doctor/formatters/unindexed_foreign_keys_formatter'

require 'inquisition/auditors/frontend/i18n_tasks/formatter'

require 'inquisition/runner'
# require 'inquisition/auditors/backend/bullet/runner'
require 'inquisition/auditors/backend/fasterer/runner'
require 'inquisition/auditors/backend/rails_best_practices/runner'
require 'inquisition/auditors/backend/reek/runner'
require 'inquisition/auditors/backend/dawnscanner/runner'
require 'inquisition/auditors/backend/bundler_audit/runner'
# require 'inquisition/auditors/backend/haml_lint/runner'
require 'inquisition/auditors/backend/lol_dba/runner'
# require 'inquisition/auditors/backend/railroady/runner'
# require 'inquisition/auditors/backend/rails_erd/runner'
require 'inquisition/auditors/backend/rubocop/runner'
# require 'inquisition/auditors/backend/rubocop_rspec/runner'
require 'inquisition/auditors/backend/ruby_lint/runner'
# require 'inquisition/auditors/backend/simplecov/runner'
# require 'inquisition/auditors/backend/slim_lint/runner'
require 'inquisition/auditors/backend/active_record_doctor/runners/extraneous_indexes_runner'
require 'inquisition/auditors/backend/active_record_doctor/runners/missing_foreign_keys_runner'
require 'inquisition/auditors/backend/active_record_doctor/runners/missing_non_null_constraint_runner'
require 'inquisition/auditors/backend/active_record_doctor/runners/missing_presence_validation_runner'
require 'inquisition/auditors/backend/active_record_doctor/runners/missing_unique_indexes_runner'
require 'inquisition/auditors/backend/active_record_doctor/runners/undefined_table_references_runner'
require 'inquisition/auditors/backend/active_record_doctor/runners/unindexed_deleted_at_runner'
require 'inquisition/auditors/backend/active_record_doctor/runners/unindexed_foreign_keys_runner'
require 'inquisition/auditors/backend/yamllint/runner'
require 'inquisition/auditors/frontend/i18n_tasks/runner'

require 'inquisition/auditors/frontend/installer'
require 'inquisition/auditors/common/installer'
