require 'inquisition/config/initializers/i18n'
require 'inquisition/outputer'
require 'inquisition/cli'

require 'inquisition/errors/base_error'
require 'inquisition/errors/base_config_absense_error'
require 'inquisition/errors/no_gem_error'
require 'inquisition/errors/no_config_file_error'
require 'inquisition/errors/invalid_ruby_version_error'
require 'inquisition/errors/additional_software_absence_error'

require 'inquisition/authorization'
require 'inquisition/builder'
require 'inquisition/configer'
require 'inquisition/base_config'

require 'inquisition/core/configer'
require 'inquisition/core/base_formatter'
require 'inquisition/core/base_installer'
require 'inquisition/core/base_runner'
require 'inquisition/core/configers/copy_file_configer'
require 'inquisition/core/configers/update_file_configer'

require 'inquisition/core/checker'
require 'inquisition/core/checkers/gem_checker'
require 'inquisition/core/checkers/exist_file_checker'
require 'inquisition/core/checkers/ruby_version_checker'
require 'inquisition/core/checkers/additional_software_checker'

require 'inquisition/auditors/installer'
require 'inquisition/auditors/backend/installer'
require 'inquisition/auditors/runner'
require 'inquisition/auditors/backend/runner'

require 'inquisition/auditors/backend/bullet/installer'
require 'inquisition/auditors/backend/fasterer/installer'
require 'inquisition/auditors/backend/haml_lint/installer'
require 'inquisition/auditors/backend/i18n_tasks/installer'
require 'inquisition/auditors/backend/lol_dba/installer'
require 'inquisition/auditors/backend/railroady/installer'
require 'inquisition/auditors/backend/rails_erd/installer'
require 'inquisition/auditors/backend/rubocop/installer'
require 'inquisition/auditors/backend/rubocop_rspec/installer'
require 'inquisition/auditors/backend/ruby_lint/installer'
require 'inquisition/auditors/backend/simplecov/installer'
require 'inquisition/auditors/backend/slim_lint/installer'
require 'inquisition/auditors/backend/yamllint/installer'

require 'inquisition/auditors/backend/rubocop/formatter'

require 'inquisition/runner'
# require 'inquisition/auditors/backend/bullet/runner'
# require 'inquisition/auditors/backend/fasterer/runner'
# require 'inquisition/auditors/backend/haml_lint/runner'
# require 'inquisition/auditors/backend/i18n_tasks/runner'
# require 'inquisition/auditors/backend/lol_dba/runner'
# require 'inquisition/auditors/backend/railroady/runner'
# require 'inquisition/auditors/backend/rails_erd/runner'
require 'inquisition/auditors/backend/rubocop/runner'
# require 'inquisition/auditors/backend/rubocop_rspec/runner'
# require 'inquisition/auditors/backend/ruby_lint/runner'
# require 'inquisition/auditors/backend/simplecov/runner'
# require 'inquisition/auditors/backend/slim_lint/runner'
# require 'inquisition/auditors/backend/yamllint/runner'

require 'inquisition/auditors/frontend/installer'
require 'inquisition/auditors/common/installer'
