require 'inquisition/cli'
require 'inquisition/core/configer'
require 'inquisition/installer'
require 'inquisition/configer'
require 'inquisition/auditors/backend/configer'
require 'inquisition/auditors/backend/fasterer/configer'
require 'inquisition/auditors/frontend/configer'
require 'inquisition/auditors/common/configer'
