source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'actionview', '5.2.2'
gem 'inquisition', path: '/var/www/inquisition'
gem 'rails'
# Use sqlite3 as the database for Active Record
gem 'pg'
gem 'pry'
gem 'puma', '~> 3.11'
gem 'rspec-rails'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
