module Inquisition
  module RailsBestPractices
    class Categorizer
      MATCH_TABLE = {
        Category::COMPLEXITY => [
          'RailsBestPractices::Reviews::AddModelVirtualAttributeReview',
          'RailsBestPractices::Reviews::DryBundlerInCapistranoReview',
          'RailsBestPractices::Reviews::IsolateSeedDataReview',
          'RailsBestPractices::Reviews::KeepFindersOnTheirOwnModelReview',
          'RailsBestPractices::Reviews::LawOfDemeterReview',
          'RailsBestPractices::Reviews::MoveCodeIntoControllerReview',
          'RailsBestPractices::Reviews::MoveCodeIntoHelperReview',
          'RailsBestPractices::Reviews::MoveCodeIntoModelReview',
          'RailsBestPractices::Reviews::MoveFinderToNamedScopeReview',
          'RailsBestPractices::Reviews::MoveModelLogicIntoModelReview',
          'RailsBestPractices::Reviews::NeedlessDeepNestingReview',
          'RailsBestPractices::Reviews::ReplaceComplexCreationWithFactoryMethodReview',
          'RailsBestPractices::Reviews::UseModelAssociationReview',
          'RailsBestPractices::Reviews::UseMultipartAlternativeAsContentTypeOfEmailReview',
          'RailsBestPractices::Reviews::UseObserverReview',
          'RailsBestPractices::Reviews::UseScopeAccessReview'
        ],
        Category::STYLE => [
          'RailsBestPractices::Lexicals::LongLineCheck',
          'RailsBestPractices::Lexicals::RemoveTabCheck',
          'RailsBestPractices::Lexicals::RemoveTrailingWhitespaceCheck',
          'RailsBestPractices::Reviews::HashSyntaxReview',
          'RailsBestPractices::Reviews::NotUseTimeAgoInWordsReview',
          'RailsBestPractices::Reviews::OveruseRouteCustomizationsReview',
          'RailsBestPractices::Reviews::ReplaceInstanceVariableWithLocalVariableReview',
          'RailsBestPractices::Reviews::RestrictAutoGeneratedRoutesReview',
          'RailsBestPractices::Reviews::SimplifyRenderInControllersReview',
          'RailsBestPractices::Reviews::UseParenthesesInMethodDefReview',
          'RailsBestPractices::Reviews::UseQueryAttributeReview',
          'RailsBestPractices::Reviews::UseSayWithTimeInMigrationsReview',
          'RailsBestPractices::Reviews::SimplifyRenderInViewsReview'
        ],
        Category::BUG_RISK => [
          'RailsBestPractices::Reviews::CheckSaveReturnValueReview',
          'RailsBestPractices::Reviews::DefaultScopeIsEvilReview',
          'RailsBestPractices::Reviews::NotRescueExceptionReview',
          'RailsBestPractices::Reviews::CheckDestroyReturnValueReview'
        ],
        Category::UNUSED_CODE => [
          'RailsBestPractices::Reviews::RemoveUnusedMethodsInControllersReview',
          'RailsBestPractices::Reviews::RemoveEmptyHelpersReview',
          'RailsBestPractices::Reviews::RemoveUnusedMethodsInHelpersReview',
          'RailsBestPractices::Reviews::RemoveUnusedMethodsInModelsReview'
        ],
        Category::PERFORMANCE => [
          'RailsBestPractices::Reviews::AlwaysAddDbIndexReview',
          'RailsBestPractices::Reviews::UseTurboSprocketsRails3Review'
        ],
        Category::SECURITY => [
          'RailsBestPractices::Reviews::ProtectMassAssignmentReview',
          'RailsBestPractices::Reviews::NotUseDefaultRouteReview'
        ],
        Category::DUPLICATION => ['RailsBestPractices::Reviews::UseBeforeFilterReview']
      }.freeze

      def self.find_category(error_type)
        MATCH_TABLE.detect { |_category, error_types| error_types.include?(error_type) }[0]
      end
    end
  end
end
