#!/usr/bin/env ruby

require 'inquisition'
require 'inquisition/cli'

CODE_INTERRUPT_EXCEPTIONS = [
  Inquisition::Errors::BaseConfigAbsenseError,
  Inquisition::Errors::NoConfigFileError,
  Inquisition::Errors::InvalidRubyVersionError,
  Inquisition::Errors::AdditionalSoftwareAbsenceError,
  Inquisition::Errors::NoGemError
].freeze

begin
  Inquisition::CLI.start(ARGV)
rescue *CODE_INTERRUPT_EXCEPTIONS => e
  puts e.message
end
