#!/usr/bin/env ruby

require 'inquisition'
require 'inquisition/cli'

CODE_INTERRUPT_EXCEPTIONS = [
  Inquisition::Error::BaseConfigAbsenseError,
  Inquisition::Error::NoConfigFileError,
  Inquisition::Error::InvalidRubyVersionError,
  Inquisition::Error::AdditionalSoftwareAbsenceError,
  Inquisition::Error::NoGemError
].freeze

begin
  Inquisition::CLI.start(ARGV)
rescue *CODE_INTERRUPT_EXCEPTIONS => e
  puts e.message
end
